-- Story 011g-b: Analytics Optimization
-- Creates materialized views and indexes for dashboard performance

-- Drop existing normal views (created by migration 2) before converting to materialized
DROP VIEW IF EXISTS v_match_rate_by_tenant_aggregated;
DROP VIEW IF EXISTS v_match_rate_by_tenant;
DROP VIEW IF EXISTS v_dispatch_summary;

-- View 1: Dispatch Summary (agregações por status/gateway)
-- Using PascalCase table names with quotes as generated by Prisma
CREATE MATERIALIZED VIEW v_dispatch_summary AS
SELECT
  d."tenantId" as tenant_id,
  d."status",
  w."gateway",
  COUNT(*) as event_count,
  AVG(EXTRACT(EPOCH FROM (d."updatedAt" - d."createdAt"))) as avg_latency_seconds,
  MIN(d."createdAt") as earliest_event,
  MAX(d."createdAt") as latest_event
FROM "DispatchAttempt" d
JOIN "WebhookRaw" w ON d."webhookRawId" = w."id"
GROUP BY d."tenantId", d."status", w."gateway";

-- Index for fast queries
CREATE UNIQUE INDEX idx_v_dispatch_summary ON v_dispatch_summary (tenant_id, status, gateway);

-- View 2: Match Rate by Tenant (taxa % diária)
CREATE MATERIALIZED VIEW v_match_rate_by_tenant AS
SELECT
  c."tenantId" as tenant_id,
  DATE(c."createdAt") as date,
  w."gateway",
  COUNT(*) as total_conversions,
  COUNT(m."id") as matched_conversions,
  ROUND(100.0 * COUNT(m."id") / NULLIF(COUNT(*), 0), 2) as match_rate_pct
FROM "Conversion" c
LEFT JOIN "WebhookRaw" w ON c."webhookRawId" = w."id"
LEFT JOIN "MatchLog" m ON c."id" = m."conversionId"
GROUP BY c."tenantId", DATE(c."createdAt"), w."gateway";

-- Index for fast queries
CREATE UNIQUE INDEX idx_v_match_rate_by_tenant ON v_match_rate_by_tenant (tenant_id, date, gateway);

-- View 3: Aggregated Match Rate (preserved from migration 2)
CREATE MATERIALIZED VIEW v_match_rate_by_tenant_aggregated AS
SELECT
  tenant_id,
  date,
  'all' as gateway,
  SUM(total_conversions) as total_conversions,
  SUM(matched_conversions) as matched_conversions,
  ROUND(100.0 * SUM(matched_conversions) / NULLIF(SUM(total_conversions), 0), 2) as match_rate_pct
FROM v_match_rate_by_tenant
GROUP BY tenant_id, date;

-- Index for aggregated view
CREATE UNIQUE INDEX idx_v_match_rate_by_tenant_aggregated ON v_match_rate_by_tenant_aggregated (tenant_id, date, gateway);

-- Performance Indexes on base tables (using correct PascalCase names with quotes)
CREATE INDEX idx_dispatch_attempts_tenant_status_created
ON "DispatchAttempt" ("tenantId", "status", "createdAt" DESC)
WHERE "status" IN ('sent', 'failed', 'retrying');

CREATE INDEX idx_matches_tenant_created
ON "MatchLog" ("tenantId", "createdAt" DESC)
WHERE "matchedAt" IS NOT NULL;

CREATE INDEX idx_conversion_tenant_gateway_created
ON "Conversion" ("tenantId", "gateway", "createdAt" DESC);

-- Table to track last refresh time for materialized views
CREATE TABLE IF NOT EXISTS materialized_view_refresh (
  view_name VARCHAR(100) PRIMARY KEY,
  last_refreshed_at TIMESTAMP DEFAULT NOW(),
  refresh_interval_minutes INT DEFAULT 5
);

INSERT INTO materialized_view_refresh (view_name, last_refreshed_at, refresh_interval_minutes)
VALUES
  ('v_dispatch_summary', NOW(), 5),
  ('v_match_rate_by_tenant', NOW(), 5),
  ('v_match_rate_by_tenant_aggregated', NOW(), 5)
ON CONFLICT (view_name) DO UPDATE SET last_refreshed_at = NOW();
